# Use the LinuxServer.io FreeCAD Docker image
FROM lscr.io/linuxserver/freecad:latest

# Set the working directory
WORKDIR /app/

# Command to execute your Python script when the container starts
#CMD ["python", "test.py"]
