version: '3'

services:
  freecad:
    build:
      context: .
    container_name: freecad
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./config:/app/config
      - ./py_scripts:/app/py_scripts
    ports:
      - "3000:3000"
      - "3001:3001"
    restart: unless-stopped
